version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: seabid_development
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/rails server -b '0.0.0.0'
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://postgres:password@db:5432/seabid_development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
  bundle_cache: 