scan_ruby:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Fix brakeman permissions ✅
      run: chmod +x bin/brakeman

    - name: Scan for common Rails security vulnerabilities using static analysis
      run: bin/brakeman --no-pager
